OENIK_PROG3_2020_2_KVRIE1/Kutyatenyeszto.WEB/Models/Institution.cs
// <copyright file="Institution.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace Kutyatenyeszto.WEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// Institution form model and insitution MVC viewmodel.
    /// </summary>
    public class Institution
    {
        /// <summary>
        /// Gets or sets primary key to identify users.
        /// </summary>
        [Display(Name = "Institution Id")]
        [Required]
        public int InstitutionId { get; set; }

        /// <summary>
        /// Gets or sets name for the institution.
        /// </summary>
        [Display(Name = "Institution Name")]
        [Required]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets address for the institution.
        /// </summary>
        [Display(Name = "Institution Address")]
        [Required]
        public string Address { get; set; }

        /// <summary>
        /// Gets or sets phone number for the institution.
        /// </summary>
        [Display(Name = "Institution Phone number")]
        [Required]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// Gets or sets director for the institution.
        /// </summary>
        [Display(Name = "Institution Director")]
        [Required]
        public string Director { get; set; }

        /// <summary>
        /// Gets or sets capacity for the institution.
        /// </summary>
        [Display(Name = "Institution Capacity")]
        [Required]
        public int Capacity { get; set; }

        /// <summary>
        /// Gets or sets capacity for the institution.
        /// </summary>
        [Display(Name = "Institution Selected")]
        public string Selected { get; set; }
    }
}

OENIK_PROG3_2020_2_KVRIE1/Kutyatenyeszto.WEB/Models/InstitutionListViewModel.cs
// <copyright file="InstitutionListViewModel.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace Kutyatenyeszto.WEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// InstitutionListViewModel class.
    /// </summary>
    public class InstitutionListViewModel
    {
        /// <summary>
        /// Gets or sets listOfInsitutions.
        /// </summary>
        public List<Institution> ListOfInsitutions { get; set; }

        /// <summary>
        /// Gets or sets editedInstitution.
        /// </summary>
        public Institution EditedInstitution { get; set; }
    }
}

OENIK_PROG3_2020_2_KVRIE1/Kutyatenyeszto.WEB/Controllers/InstitutionsController.cs
// <copyright file="InstitutionsController.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace Kutyatenyeszto.WEB.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using AutoMapper;
    using Kutyatenyeszto.Logic;
    using Kutyatenyeszto.WEB.Models;
    using Microsoft.AspNetCore.Mvc;

    /// <summary>
    /// Controller class.
    /// </summary>
    public class InstitutionsController : Controller
    {
        private readonly IManagementLogic manage;
        private readonly IDisplayLogic display;
        private readonly IMapper mapper;
        private readonly InstitutionListViewModel vm;

        /// <summary>
        /// Initializes a new instance of the <see cref="InstitutionsController"/> class.
        /// </summary>
        /// <param name="manage">IManagementLogic type element.</param>
        /// <param name="display">IDisplayLogic type element.</param>
        /// <param name="mapper">IMapper type element.</param>
        public InstitutionsController(IManagementLogic manage, IDisplayLogic display, IMapper mapper)
        {
            this.manage = manage;
            this.display = display;
            this.mapper = mapper;

            this.vm = new InstitutionListViewModel
            {
                EditedInstitution = new Models.Institution(),
            };

            var institutions = display.GetAllInstitutions();
            this.vm.ListOfInsitutions = mapper.Map<IList<Data.Models.Institution>, List<WEB.Models.Institution>>(institutions);
        }

        /// <summary>
        /// Index method.
        /// </summary>
        /// <returns>IActionResult type element.</returns>
        public IActionResult Index()
        {
            this.ViewData["editAction"] = "AddNew";
            return this.View("InstitutionIndex", this.vm);
        }

        /// <summary>
        /// Details method.
        /// </summary>
        /// <param name="id">int type element.</param>
        /// <returns>IActionResult type element.</returns>
        public IActionResult Details(int id)
        {
            return this.View("InstitutionDetails", this.GetInstitutionModel(id));
        }

        /// <summary>
        /// Remove method.
        /// </summary>
        /// <param name="id">int type element.</param>
        /// <returns>IActionResult type element.</returns>
        public IActionResult Remove(int id)
        {
            this.manage.DeleteInstitution(id);
            this.TempData["editResult"] = "Delete OK";
            return this.RedirectToAction(nameof(this.Index));
        }

        /// <summary>
        /// Remove method.
        /// </summary>
        /// <param name="id">int type element.</param>
        /// <returns>IActionResult type element.</returns>
        public IActionResult Edit(int id)
        {
            this.ViewData["editAction"] = "Edit";
            this.vm.EditedInstitution = this.GetInstitutionModel(id);
            return this.View("InstitutionIndex", this.vm);
        }

        /// <summary>
        /// Edit method.
        /// </summary>
        /// <param name="institution">Institution type element.</param>
        /// <param name="editAction">string type element.</param>
        /// <returns>IActionResult type element.</returns>
        [HttpPost]
        public IActionResult Edit(Models.Institution institution, string editAction)
        {
            if (this.ModelState.IsValid && institution != null)
            {
                this.TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    Data.Models.Institution insert = new ()
                    {
                        Name = institution.Name,
                        Address = institution.Address,
                        PhoneNumber = institution.PhoneNumber,
                        Director = institution.Director,
                        Capacity = institution.Capacity,
                    };
                    this.manage.InsertInstitution(insert);
                }
                else
                {
                    Data.Models.Institution insert = new ()
                    {
                        InstitutionId = institution.InstitutionId,
                        Name = institution.Name,
                        Address = institution.Address,
                        PhoneNumber = institution.PhoneNumber,
                        Director = institution.Director,
                        Capacity = institution.Capacity,
                    };
                    this.manage.UpdateInstitution(insert, insert.InstitutionId);
                }

                return this.RedirectToAction(nameof(this.Index));
            }
            else
            {
                this.ViewData["editAction"] = "Edit";
                this.vm.EditedInstitution = institution;
                return this.View("InstitutionIndex", this.vm);
            }
        }

        private Models.Institution GetInstitutionModel(int id)
        {
            Data.Models.Institution oneInstitution = this.display.GetOneInstitution(id);
            return this.mapper.Map<Data.Models.Institution, Models.Institution>(oneInstitution);
        }
    }
}

OENIK_PROG3_2020_2_KVRIE1/Kutyatenyeszto.WEB/Views/Institutions/InstitutionDetails.cshtml
@model Kutyatenyeszto.WEB.Models.Institution;

@{
    ViewData["Title"] = "InstitutionDetails";
}

<h2>Datasheet of one institution</h2>

@Html.ActionLink("Back to the list", "Index")

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.InstitutionId)</td>
        <td>@Html.DisplayFor(m => m.InstitutionId)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Name)</td>
        <td>@Html.DisplayFor(m => m.Name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Address)</td>
        <td>@Html.DisplayFor(m => m.Address)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.PhoneNumber)</td>
        <td>@Html.DisplayFor(m => m.PhoneNumber)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Director)</td>
        <td>@Html.DisplayFor(m => m.Director)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Capacity)</td>
        <td>@Html.DisplayFor(m => m.Capacity)</td>
    </tr>
</table>

OENIK_PROG3_2020_2_KVRIE1/Kutyatenyeszto.WEB/Views/Institutions/InstitutionEdit.cshtml
@model Kutyatenyeszto.WEB.Models.Institution

<h2>Institution Edit</h2>

@using (Html.BeginForm("Edit", "Institutions"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.InstitutionId)

    @Html.Hidden("editAction", ViewData["editAction"].ToString())

    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Address)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Address)</div>

    <div class="editor-label">@Html.LabelFor(m => m.PhoneNumber)</div>
    <div class="editor-field">@Html.EditorFor(m => m.PhoneNumber)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Director)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Director)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Capacity)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Capacity)</div>

    <input type="submit" value="SEND" />
}

OENIK_PROG3_2020_2_KVRIE1/Kutyatenyeszto.WEB/Views/Institutions/InstitutionIndex.cshtml
@model Kutyatenyeszto.WEB.Models.InstitutionListViewModel

@{
    ViewData["Title"] = "Crud Index";
}

<h2>Institution Index</h2>

<p style="color:red">@TempData["editResult"]</p>

@await Html.PartialAsync("InstitutionEdit", Model.EditedInstitution)

@await Html.PartialAsync("InstitutionList", Model.ListOfInsitutions)

OENIK_PROG3_2020_2_KVRIE1/Kutyatenyeszto.WEB/Views/Institutions/InstitutionList.cshtml
@model IEnumerable<Kutyatenyeszto.WEB.Models.Institution>

<h2>Institution List</h2>

@if (Model.Count() == 0)
{
    <p> No data in the database</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Name)</th>
            <th>@Html.DisplayNameFor(m => m.First().Address)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Modify</th>
        </tr>
        @foreach (var institution in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => institution.Name)</td>
                <td>@Html.DisplayFor(m => institution.Address)</td>
                <td>@Html.ActionLink("[SHOW]", "Details", new { id = institution.InstitutionId})</td>
                <td>@Html.ActionLink("[DEL]", "Remove", new { id = institution.InstitutionId})</td>
                <td>@Html.ActionLink("[EDIT]", "Edit", new { id = institution.InstitutionId})</td>
            </tr>
        }
    </table>
}